---
title: "STRING Screening"
author: "Lorenzo Gesuita"
date: "18/07/2022"
output: html_document
---

```{r message=FALSE, warning=FALSE, include=FALSE}

# choose a folder and set it as your working directory (wd) indicating its path below; be sure to have a "/" at the end of the string.

wd <- "~/Documents/University_of_Zurich_PhD/Lab/ProjectB_Microglia/STRING_Screening/STRING screening_Github Version/"
setwd(wd)

library(data.table)
library(matrixStats)
library(tidyverse)
library(dplyr)

```


# LOAD AND PREPARE STRING DATABASE
```{r}

# upload the STRING interaction table (version 11.0)
STRING <- fread(paste0(wd,"datasets/10090.protein.actions.v11.0.txt"), select = c("item_id_a","item_id_b","mode","score"))
STRING <- distinct(STRING) #remove duplicated rows

# add the experimental score to the STRING interaction table
STRING_SingleScores <- read.table(paste0(wd,"datasets/10090.protein.links.detailed.v11.0.txt"), header = TRUE)
STRING_SingleScores$pasted <- paste(STRING_SingleScores$protein1, STRING_SingleScores$protein2, sep = "_")
STRING$pasted <- paste(STRING$item_id_a, STRING$item_id_b, sep = "_")
STRING$experimental_score <- STRING_SingleScores[match(STRING$pasted, STRING_SingleScores$pasted),7]
STRING$pasted <- NULL

# upload the Alias reference table and keep the "ENSMUSG" IDs only
Alias <- fread(paste0(wd,"datasets/10090.protein.aliases.v11.0.txt"),select = c("string_protein_id","alias"))
Alias <- Alias[grep("ENSMUSG", Alias$alias), ]
Alias <- Alias[!grep("Predicted gene", Alias$alias), ]

# add the ENSMUSG IDs to the STRING interaction table
STRING$gene_id_a=Alias[match(STRING$item_id_a, Alias$string_protein_id),2]
STRING$gene_id_b=Alias[match(STRING$item_id_b, Alias$string_protein_id),2]

# subset for the type of interaction
STRING <- subset(STRING, mode == "binding")

# subset for confidence score > 400 and experiemental score > 0
STRING <- subset(STRING, score >= 400 )
STRING <- subset(STRING, experimental_score > 0 )

# add those cytokine interecations annotated in Uniprot (we gave arbitrary confidential score = 701 and experimental score = 10)
STRING_manual1 <- fread(paste0(wd,"datasets/ManualSTRING_Cytokine.txt"), select = c("item_id_a","item_id_b","mode","score","gene_id_a","gene_id_b","experimental_score"))

STRING_manual2 <- fread(paste0(wd,"datasets/ManualSTRING_Cytokine.txt"), select = c("item_id_b","item_id_a","mode","score","gene_id_b","gene_id_a","experimental_score"))
names(STRING_manual2) <- c("item_id_a","item_id_b","mode","score","gene_id_a","gene_id_b","experimental_score")

STRING <- rbind(STRING,STRING_manual1,STRING_manual2)

rm(STRING_SingleScores)
rm(STRING_manual1)
rm(STRING_manual2)

```


# LOAD AND PREPARE UNIPROT LISTS OF RECEPTORS AND LIGANDS
```{r}

# upload receptor list
Uniprot <- read.table(paste0(wd,"datasets/CellMembrane_ExtracellularDomain_Receptor.txt"),head = TRUE)
Uniprot <- subset(Uniprot, !STRING_ID == "NO_STRING_ID")

# add the ENSMUSG IDs next to the STRING_ID
Uniprot$gene_id = Alias[match(Uniprot$STRING_ID,Alias$string_protein_id),2]
colnames(Uniprot)[3] <- "gene_id"

# keep ENSMUSG IDs only
Uniprot <- pull(Uniprot[,3])
Uniprot <- na.omit(Uniprot)
Uniprot <- unique(Uniprot)

Uniprot_Receptor <- Uniprot

rm(Uniprot)


# upload ligand list
a <- read.table(paste0(wd, "datasets/CellMembrane_ExtracellularDomain_NotReceptor.txt"),head = TRUE) 
b <- read.table(paste0(wd, "datasets/Secreted.txt"),head = TRUE)
Uniprot <- rbind(a,b)

Uniprot <- subset(Uniprot, !STRING_ID == "NO_STRING_ID")

# add the ENSMUSG IDs next to the STRING_ID
Uniprot$gene_id = Alias[match(Uniprot$STRING_ID,Alias$string_protein_id),2]
colnames(Uniprot)[3] <- "gene_id"

# keep ENSMUSG IDs only
Uniprot <- pull(Uniprot[,3])
Uniprot <- na.omit(Uniprot)
Uniprot <- unique(Uniprot)

Uniprot_Secreted <- Uniprot

rm(Uniprot)
rm(a)
rm(b)

```


### LOAD AND PREPARE RNA Seq DATA
```{r}
# upload gene names - ENSMUSG conversion table
GenesList <- read.table(paste0(wd,"datasets/Gene_list.txt"),head = TRUE)

# upload microglia sequencing data
MIC <- read.csv(paste0(wd,"datasets/GSE79812_Timeline.csv"),head = TRUE)

#add ENSMUSG IDs
MIC$Feature_ID <- GenesList[match(MIC$Symbol, GenesList$gene_name),1]

# add a column with the mean of expression levels at P9
MIC$MIC_Mean <- rowMeans(as.matrix(MIC[,25:26])) 

# filter genes over the threshold
MIC <- subset(MIC,MIC$MIC_Mean >= 30)

# filter genes for uniprot categories
MIC_Receptor <- subset(MIC,Feature_ID %in% Uniprot_Receptor)
MIC_Secreted <- subset(MIC,Feature_ID %in% Uniprot_Secreted)



# upload neuronal sequencing data
NEU <- read.csv(paste0(wd,"datasets/GSE120161_fpkm_replicates.csv"),head = TRUE)

# add a column with the mean of expression levels
NEU$SS10_Mean <- rowMeans(as.matrix(NEU[,18:20]))
NEU$PV10_Mean <- rowMeans(as.matrix(NEU[,9:11]))
NEU$Pyr12_Mean <- rowMeans(as.matrix(NEU[,24:26]))

# filter genes over the threshold
SST <- subset(NEU,NEU$SS10_Mean >= 30)
PV <- subset(NEU,NEU$PV10_Mean >= 30)
PYR <- subset(NEU,NEU$Pyr12_Mean >= 30)

# filter genes for uniprot categories
SST_Secreted <- subset(SST,Feature_ID %in% Uniprot_Secreted)
SST_Receptor <- subset(SST,Feature_ID %in% Uniprot_Receptor)

PV_Secreted <- subset(PV,Feature_ID %in% Uniprot_Secreted)
PV_Receptor <- subset(PV,Feature_ID %in% Uniprot_Receptor)

PYR_Secreted <- subset(PYR,Feature_ID %in% Uniprot_Secreted)
PYR_Receptor <- subset(PYR,Feature_ID %in% Uniprot_Receptor)

```


### BUILD TH INTERACTOME
```{r}
for (i in 1:3) {
  
if (i == 1) {
  WhichCell <- "SST"
  NEU_Receptor <- SST_Receptor
  NEU_Secreted <- SST_Secreted
  }
if (i == 2) {
  WhichCell <- "PV"
  NEU_Receptor <- PV_Receptor
  NEU_Secreted <- PV_Secreted
  }
if (i == 3) {
  WhichCell <- "Pyramidal"
  NEU_Receptor <- PYR_Receptor
  NEU_Secreted <- PYR_Secreted
  }


# Create the interactome between the selected neuronal type (gene_id_a) and microglia (gene_id_b)
Interactions <- subset(STRING, gene_id_a %in% NEU_Receptor$Feature_ID) 
InteractionsA <- subset(Interactions, gene_id_b %in% MIC_Secreted$Feature_ID)

Interactions <- subset(STRING, gene_id_a %in% NEU_Secreted$Feature_ID) 
InteractionsB <- subset(Interactions, gene_id_b %in% MIC_Receptor$Feature_ID)

Interactions <- rbind(InteractionsA,InteractionsB)

Interactions$NEU_GeneName = GenesList[match(Interactions$gene_id_a, GenesList$Identifier),2]
Interactions$MIC_GeneName = GenesList[match(Interactions$gene_id_b, GenesList$Identifier),2]


# remove reciprocal interactions
Interactions$pasted1 <- paste(Interactions$gene_id_a, Interactions$gene_id_b, sep = "_")
Interactions$pasted2 <- paste(Interactions$gene_id_b, Interactions$gene_id_a, sep = "_")
pasted1 <- as.vector(Interactions$pasted1)
pasted2 <- as.vector(Interactions$pasted2)
pasted <- c(pasted1,pasted2)
pasted <- pasted[!(duplicated(pasted)|duplicated(pasted, fromLast=TRUE))]
      
Interactions <- subset(Interactions, Interactions$pasted1 %in% pasted)
Interactions$pasted1 <- NULL
Interactions$pasted2 <- NULL


# create the output file:
OUT_FileName <- paste0("Output_",WhichCell," vs ","Microglia",".csv") 
write.csv(Interactions, file = OUT_FileName)

}

```
